config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ex_cals#index'

  # resources :countdowns
  resources :ex_cals

  # resources :countdowns do
  #   resources :ex_cals, only: [:index, :show]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/countdown.rb
class Countdown < ApplicationRecord
rend

app/models/countdown_ex_cal.rb
class CountdownExCal < ApplicationRecord
    belongs_to :countdown
    belongs_to :ex_cal
end

app/models/ex_cal.rb
class ExCal < ApplicationRecord

    def self.total_calories_left(total_calories_burned)
        770000 - total_calories_burned
    end

    def self.total_calories_burned
        self.all.collect {|tb| tb.calories_burned unless tb == nil}.flatten.sum
    end

    def self.total_days_left
        # @finish_date = Date.parse("9/25/2027")
        # @current_date = Date.current.to_s
        # (@finish_date.to_i - @original_date.to_i)
        a = Date.parse("25/9/2027") - Date.current
        a.to_s.chomp("/1")
    end

    # def self.total_calories_left_per_day
    #     self.total_days_left.to_i / self.total_calories_left.to_s.to_i
    # end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ex_cals_controller.rb
class ExCalsController < ApplicationController
    layout "standard"
    
    def index
        @ex_cals = ExCal.all

        @total_calories_burned = ExCal.total_calories_burned
        @total_calories_left = ExCal.total_calories_left(@total_calories_burned)
        @total_days_left = ExCal.total_days_left
        @total_calories_left_per_day = @total_calories_left / @total_days_left.to_i
    end

    def new
        @ex_cal = ExCal.new
    end

    def create
        @ex_cal = ExCal.new(params[:ex_cal].permit(:calories_burned, :notes))
        # (calories_burned: params[:ex_cals][:calories_burned], notes: params[:ex_cals][:notes])
        @ex_cal.save
        redirect_to @ex_cal
    end
    
    def show
        # @countdown = Countdown.find_by(id: params[:countdown_id])
        # @ex_cal = @countdown.ex_cals.find_by(id: params[:id] )
        @ex_cal = ExCal.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ex_cals/index.html.erb
<p>Total Calories Left</p> 
<p><%= number_with_delimiter(@total_calories_left, :delimiter => ',') %></p><br>

<p>Total Calories Burned</p> 
<p><%= number_with_delimiter(@total_calories_burned, :delimiter => ',') %></p><br>

<p>Total Days Left</p>
<p><%= number_with_delimiter(@total_days_left, :delimiter => ',') %></p><br>

<p>Total Calories Left Per Day</p> 
<p><%= number_with_delimiter(@total_calories_left_per_day, :delimiter => ',') %></p><br>
<%# <%= @total_calories_per_day_left %>
<%# <%= @total_calories_per_day_burned %>

<h4><%= link_to "New Entry", new_ex_cal_path %></h4><br>

<h3>All entries</h3>
    <ol>
<% @ex_cals.each do |ec| %>
        <li><%= ec.created_at %> - <%= ec.calories_burned %> - <%= ec.notes %></li><br>
<% end %>
    </ol>

app/views/ex_cals/new.html.erb
<h2>Make an entry</h2>

<%= form_for @ex_cal do |f| %>
<%= f.select([:calories_burned]) %>
<%# # , grouped_options_for_select("333"))  %>
<%# grouped_options_for_select [['Fruits',  @fruits.collect {|v| [ v.name, v.id ] }],
                            ['Veggies', @veggies.collect {|v| [ v.name, v.id ] }],
                            ['Junk',    @junk_food.collect {|v| [ v.name, v.id ] }]]f.select :food_attribute, grouped_options_for_select(...) %>
<%# ["North America",[["United States","US"],["Canada","CA"]]] %>
<%# <%= f.options_for_select([["calories_burned", "333"], ["calories_burned", "363"]]) %> %>
<%# <%= f.collection_select :itself, ExCal.all.sort { |x,y| y <=> x }, :id, :calories_burned %> %>
<%= f.label "Calories Burned" %><br><br>
<%= f.text_field :calories_burned %><br><br>
<%= f.label "Notes" %><br><br>
<%= f.text_area :notes %><br><br>
<%= f.submit "Submit" %>
<% end %><br>

<a href="https://docs.google.com/spreadsheets/d/1eAkTu1JQ8Zvv-ksYif3j1sRZlyrJxaRq1LRr6x5Kepk/edit?usp=sharing">Calorie Key</a></a>

app/views/ex_cals/show.html.erb
<h2>New entry</h2>


Date: <%= @ex_cal.created_at%><br><br>

Calories Burned: <%= @ex_cal.calories_burned %><br><br>

Notes: <%= @ex_cal.notes %><br><br>

<h4><%= link_to "New Entry ", ex_cals_path %></h4>

<h4><%= link_to "Home", root_path %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Exercise Calorie Countdown</title>
      <%= javascript_include_tag "application" %>
      <%= stylesheet_link_tag "application" %>
   </head>

   <body id = "excalcountdown">
      <div id = "container">
         
         <div id = "header">
            <h1>Exercise Calorie Countdown</h1>
            <h3>Exercise for the Long Game</h3>
         </div>

         <div id = "content">
            <%= yield -%>
         </div>

         <div id = "sidebar"></div>
         
      </div>
   </body>
   
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Exercise Calorie Countdown</title>
      <%= stylesheet_link_tag "style" %>
   </head>

   <body id = "excalcountdown">
      <div id = "container">
         
         <div id = "header">
            <h1>Exercise Calorie Countdown</h1>
            <h3>A Calorie Counter for Long Game Weight Loss</h3>
         </div>

         <div id = "content">
            <%= yield -%>
         </div>

         <div id = "sidebar"></div>
         
      </div>
   </body>
   
</html>